default: &default
  adapter: postgresql
  encoding: unicode
  username: italo
  password: italo
  pool: 5
  timeout: 5000
  host: localhost
development:
  <<: *default
  database: rorapi_development
production:
  <<: *default
  database: rorapi-production
